### ISSUE TITLE
Taming harpies cause crash

### ISSUE THREAD

**Issue by DaRubb3rDucky1** [SodiumZH/Days-with-Monster-Girls#24] opened 2024-02-23 21:49 UTC
Tittle is pretty self-explanatory. Trying to tame a harpy causes the game crash and say this.
```
The game crashed whilst ticking entity
Error: java.lang.NoSuchMethodError: 'int com.github.mechalopa.hmag.world.entity.HarpyEntity.getVariant()'
```
I tried taming it with golden apples. It only crashes when the strength level goes to 5 or above (Going from strength 4 -> 5 or 5 -> 6)
[crash-2024-02-23_16.44.54-server.txt](https://github.com/SodiumZH/Days-with-Monster-Girls/files/14390373/crash-2024-02-23_16.44.54-server.txt)

**Comment by SodiumZH** [comment] 2024-02-24 16:53
This is possibly caused by HMaG API update. I'll check it.

**Comment by SodiumZH** [comment] 2024-03-24 11:29
Fixed in 0.x.22.

**Closed as completed by SodiumZH** 2024-03-24 11:29 UTC
Labels: confirmed bug
