### ISSUE TITLE
Necromancer wand crash

### ISSUE THREAD

**Issue by TopHatSerpent2020** [SodiumZH/Days-with-Monster-Girls#25] opened 2024-03-11 18:23 UTC
For some reason whenever I use the Necromancer wand it crashes my game, At first I thought it was another mod conflicting with it but I tried just only having the dwmg mod and the HMaG (and also dwmg mod of course) mods in and it still crashed. 
The version of Minecraft I'm on is 1.20.1 and the version of forge I'm using is 47.2.0

Here's the crash report (also been a while since I've used pastebin so I hope the link works right) 
https://pastebin.com/epqt3iFS

**Comment by SodiumZH** [comment] 2024-03-16 13:52
Caused by HMaG API change in the latest versions. Will be fixed in the next version.

**Comment by SodiumZH** [comment] 2024-03-24 11:29
Fixed in 0.x.22.

**Closed as completed by SodiumZH** 2024-03-24 11:29 UTC
Labels: confirmed bug
